#!/bin/bash

set -e

ALASKA="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/../"

source ${ALASKA}/enable
source ${ALASKA}/.config

LIB=lib/libalaska_library.a
OUTFILE="a.out"
KEEP="false"
BASELINE="false"
COLLECT_CLANG_ARGS=() INPUTS=()
OBJECT_TARGET=

SO="so"
if [ "$(uname)" == "Darwin" ]; then
	SO="dylib"
fi

phase="link"

while [[ $# -gt 0 ]]
do
    case $1 in
			-b|--baseline)
				BASELINE="true"
				shift
				;;
			-k|--keep-ir)
				KEEP="true"
				shift
				;;
			-o)
				OUTFILE="$2"
				shift
				shift
				COLLECT_CLANG_ARGS+=("-o $OUTFILE")
				;;
			-c)
				phase="compile"
				shift
				;;
			*)
				COLLECT_CLANG_ARGS+=("$1")
				shift
				;;
    esac
done


if [ "$phase" = "compile" ]; then
	gclang -I${ALASKA}/runtime/include -c ${COLLECT_CLANG_ARGS[@]}
	exit
else
	# If the program is being linked, link it as the user requests, then
	# use get-bc to run our pass on it behind the scenes :)
	gclang -lm -I${ALASKA}/runtime/include ${COLLECT_CLANG_ARGS[@]} "${ALASKA}/build/$LIB"
	get-bc $OUTFILE >/dev/null
	[ "$BASELINE" == "true" ] && mv $OUTFILE $OUTFILE.baseline
	TMPFILE=${OUTFILE}.bc
	[ "$KEEP" == "true" ] && llvm-dis ${TMPFILE} -o ${OUTFILE}.in.ll


	AA="--basic-aa --globals-aa --cfl-steens-aa --tbaa --cfl-anders-aa -scev-aa "
	LOOPS="-loops -loop-simplify -lcssa -domtree -scalar-evolution"
	AA=""
	LOOPS=""

	# Run a cleanup pass on the bitcode
	opt ${AA} \
		-mem2reg \
		-simplifycfg-sink-common=false \
		-sink \
		-lowerswitch \
		-mergereturn \
		--break-crit-edges \
		-loop-simplify \
		-lcssa \
		-gvn \
		-indvars \
		--function-attrs \
		--rpo-function-attrs "${TMPFILE}" -o "${TMPFILE}"

	# Run a simple normalization pass on the code
	opt -load "${ALASKA}/build/AlaskaNormalize.$SO" \
		--alaska-norm                                \
		-enable-new-pm=0                             \
		"${TMPFILE}" -o "${TMPFILE}" 

	# Run the main pin pass over the code
	opt -load "${ALASKA}/build/Alaska.$SO" \
		-domtree                             \
		$AA                                  \
		--alaska                             \
		-enable-new-pm=0                     \
		"${TMPFILE}" -o "${TMPFILE}" 


	llvm-link -o ${TMPFILE} ${TMPFILE} ${ALASKA}/build/lib/alaska.bc

	opt ${AA} \
		-mem2reg \
		-simplifycfg-sink-common=false \
		-sink \
		-lowerswitch \
		-mergereturn \
		--break-crit-edges \
		-loop-simplify \
		-lcssa \
		-gvn \
		-indvars \
		--function-attrs \
		--rpo-function-attrs "${TMPFILE}" -o "${TMPFILE}"
	

	[ "$KEEP" == "true" ] && llvm-dis ${TMPFILE} -o ${OUTFILE}.out.ll


	clang -T "${ALASKA}/compiler/linkerscripts/alaska-aarch64.ld" -lm -O3 -g -march=native ${TMPFILE} "${ALASKA}/build/$LIB" -o $OUTFILE

	rm ${TMPFILE}
fi

