#!/bin/bash
set -e

if [ $# -eq 0 ]
  then
    echo "usage: noelle-autoprof <in.bc> [profile args...]"
    echo "       emits 'profiled.bc' after running with the provided arguments"
		exit
fi

ALASKA="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/../"
source ${ALASKA}/dep/noelle/enable

INPUT=$1
shift

NORMALIZED=$(mktemp)
PROFILEBIN=$(mktemp)

# normalize the bitcode
noelle-norm ${INPUT} -o ${NORMALIZED} >/dev/null
echo "Normalized to ${NORMALIZED}"

noelle-prof-coverage "${NORMALIZED}" "${PROFILEBIN}" -lstdc++
echo "Built profile binary to ${PROFILEBIN}"


${PROFILEBIN} $@ &>/dev/null
echo "Ran the profile binary with args $@"

noelle-meta-prof-embed default.profraw "${NORMALIZED}" -o profiled.bc
echo "Embedded profile information"

rm ${NORMALIZED} ${PROFILEBIN} default.profraw
