name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Configure
      run: nix develop --command make defconfig

    - name: Compile
      run: nix develop --command make

    - name: Run Tests
      run: nix develop --command make test
