name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Configure
      shell: nix develop --command {0}
      run: |
         mkdir -p build && cd build && cmake ../ -DALASKA_ENABLE_COMPILER=OFF          \
                                                 -DALASKA_ENABLE_TESTING=ON            \
                                                 -DCMAKE_INSTALL_PREFIX:PATH=../local

    - name: Compile
      shell: nix develop --command {0}
      run: |
        make -C build install

    - name: Test
      shell: nix develop --command {0}
      run: |
        build/runtime/alaska_test
